PLANT_ANNOTATION_STRING = "Plant_Flora"
ANIMAL_ANNOTATION_STRING = "Animal_Fauna"
LOCATION_ANNOTATION_STRING = "Location_Place"
TAXON_ANNOTATION_STRING = "Taxon"

ANNOTATION_PRIORITY = [
    PLANT_ANNOTATION_STRING,
    ANIMAL_ANNOTATION_STRING,
    TAXON_ANNOTATION_STRING,
    LOCATION_ANNOTATION_STRING,
]
